@startuml
skinparam monochrome true
skinparam padding 1
start
package "Build" {
    :01.Git에서 소스 로딩;
    :02.실행파일 생성;
}
package "Test" {
      :03.테스트/코드 거버리지 측정;
      if (테스트 통과?) then (no)
          stop
      endif
  
    :04.보안 취약성 검사(Sparrow);
    :05.소스 품질 검사(SonarQube);
  
    :06.품질 검사 만족 판단;
    if (Quality Gate 통과?) then (no)
        stop
    endif
}

package "Build image" {
    :07.컨테이너 이미지 생성;
    :08.이미지 보안성 검사;
    if (심각한 취약성 발견?) then (yes)
        stop
    endif
}

package "Release" {
    :09.컨테이너 이미지 푸시;
}

package "Deploy" {
    :10.배포 매니페스트 파일 생성;
    :11.클러스터에 서비스 배포;
    :12.완료 통보(Slack);
}
stop
@enduml
